
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * To change this license header`, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ozcanonur
 */
public class MainFrame extends javax.swing.JFrame
{

    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        filenameLabel = new javax.swing.JLabel();
        numberofcontigLabel = new javax.swing.JLabel();
        averagecontigLabel = new javax.swing.JLabel();
        totallengthLabel = new javax.swing.JLabel();
        largestcontigLabel = new javax.swing.JLabel();
        shortestcontigLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        overallGCLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        N50Label = new javax.swing.JLabel();
        GraphPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contigsList = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        contigSequenceTextArea = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        gffTable = new javax.swing.JTable();
        GffLabel = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        selectedContigLengthLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        selectedContigGCLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        uploadGFFButton = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel1.setText("Filename:");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel2.setText("Number of contigs:");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel3.setText("Avg contig:");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel4.setText("Total length:");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel6.setText("Largest contig:");

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel7.setText("Shortest contig:");

        filenameLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        filenameLabel.setText("N/A");

        numberofcontigLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        numberofcontigLabel.setText("N/A");

        averagecontigLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        averagecontigLabel.setText("N/A");

        totallengthLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        totallengthLabel.setText("N/A");

        largestcontigLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        largestcontigLabel.setText("N/A");

        shortestcontigLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        shortestcontigLabel.setText("N/A");

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel12.setText("Overall GC%:");

        overallGCLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        overallGCLabel.setText("N/A");

        jLabel14.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel14.setText("General Statistics");

        jLabel16.setText("(Colored red on graph)");

        jLabel18.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("N50:");

        N50Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        N50Label.setText("N/A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filenameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N50Label, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(largestcontigLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shortestcontigLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totallengthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overallGCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberofcontigLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(averagecontigLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filenameLabel)
                    .addComponent(jLabel18)
                    .addComponent(N50Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberofcontigLabel)
                    .addComponent(jLabel6)
                    .addComponent(largestcontigLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(averagecontigLabel)
                    .addComponent(jLabel7)
                    .addComponent(shortestcontigLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totallengthLabel)
                    .addComponent(jLabel12)
                    .addComponent(overallGCLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GraphPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GraphPanel.setLayout(new javax.swing.BoxLayout(GraphPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setText("Contig List");

        contigsList.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(contigsList);

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel9.setText("Contig Sequence");

        contigSequenceTextArea.setEditable(false);
        contigSequenceTextArea.setColumns(20);
        contigSequenceTextArea.setFont(new java.awt.Font("Consolas", 0, 9)); // NOI18N
        contigSequenceTextArea.setLineWrap(true);
        contigSequenceTextArea.setRows(5);
        jScrollPane3.setViewportView(contigSequenceTextArea);

        jLabel17.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel17.setText("Contig Hits");

        gffTable.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        gffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Node", "Type", "Start", "End", "Score"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(gffTable);

        GffLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        GffLabel.setText("Filename: N/A");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 334, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(GffLabel)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17)
                    .addComponent(GffLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        uploadButton.setText("Upload Fasta");
        uploadButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                uploadButtonActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel10.setText("Selected Contig Statistics");

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel11.setText("Contig length:");

        selectedContigLengthLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        selectedContigLengthLabel.setText("N/A");

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel13.setText("GC% content:");

        selectedContigGCLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        selectedContigGCLabel.setText("N/A");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedContigLengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedContigGCLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                .addGap(79, 79, 79))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(selectedContigLengthLabel)
                    .addComponent(jLabel13)
                    .addComponent(selectedContigGCLabel))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jLabel15.setText("(These might take a while..)");

        uploadGFFButton.setText("Upload GFF");
        uploadGFFButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                uploadGFFButtonActionPerformed(evt);
            }
        });

        jPanel25.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uploadButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uploadGFFButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadButton)
                    .addComponent(uploadGFFButton)
                    .addComponent(jLabel15))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_uploadButtonActionPerformed
    {//GEN-HEADEREND:event_uploadButtonActionPerformed
      
        //<editor-fold defaultstate="collapsed" desc="File Chooser for .fasta">
        
        //Create File chooser
        JFileChooser chooser = new JFileChooser();
              
        //Adding a filter that only accepts the relevant file type
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "FASTA File", "fasta");
        
        chooser.setFileFilter(filter);
        int confirm = chooser.showOpenDialog(null);
        File file = null;
        //If something is selected
        if(JFileChooser.APPROVE_OPTION == confirm)
        {
            //Get the chosen file
            file = chooser.getSelectedFile();
            
            filenameLabel.setText(file.getName());
        }
        else
            JOptionPane.showMessageDialog(null, "Please select a valid fasta file");
            
            
//</editor-fold>
            
        //Parsing the fasta file into contigs
        List<Contig> contigs = Util.parseFasta(file);
                  
        //<editor-fold defaultstate="collapsed" desc="General Statistics">
        
        //Show number of contigs
        int numberOfContigs = contigs.size();
        numberofcontigLabel.setText(Integer.toString(numberOfContigs));
        
        //Show average contig length
        int averageContigLength = Util.averageContigLength(contigs);
        averagecontigLabel.setText(Integer.toString(averageContigLength)+" bp");
        
        //Show total length
        int totalLength = Util.totalLength(contigs);
        totallengthLabel.setText(Integer.toString(totalLength)+" bp");
        
        //Show largest contig length
        int largestContig = contigs.get(0).getLength();
        largestcontigLabel.setText(Integer.toString(largestContig)+" bp");
        
        //Show the shortest contig length
        int shortestContig = contigs.get(contigs.size()-1).getLength();
        shortestcontigLabel.setText(Integer.toString(shortestContig)+" bp");
        
        //Show total GC
        float GC = Util.totalGC(contigs);
        overallGCLabel.setText(Float.toString(GC).substring(0,5) + "%");
        
        //Show N50
        int N50 = Util.findN(contigs, totalLength,50);    
        N50Label.setText(Integer.toString(N50) + " bp");
        

//</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc="List of contigs">
        
        //Showing the list of contigs
        Vector<String> contigNames = new Vector<>();
        for(Contig fasta:contigs)
            contigNames.add(fasta.getName());
        
        contigsList.setListData(contigNames);
//</editor-fold>
               
        //<editor-fold defaultstate="collapsed" desc="MouseClick listener for the list of contigs">

        //Adding action listener to items in contigs list
        MouseListener mouseListener = new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                String selectedItem = (String) contigsList.getSelectedValue();
                
                Contig selectedFasta = new Contig();
                for(Contig fasta:contigs)
                {
                    if(fasta.getName().equals(selectedItem))
                        selectedFasta = fasta;
                }
                
                //Show the statistics for selected config and the sequence
                String sequence = selectedFasta.getSequence();
                contigSequenceTextArea.setText(sequence);
                
                selectedContigGCLabel.setText(Float.toString(selectedFasta.getGC()) + "%");
                
                selectedContigLengthLabel.setText(Integer.toString(selectedFasta.getLength()) + " bp");
                
                //Create a new GFF object list for the selected contig, display the list for that contig name
                List<GFF> selectedContigGFFList = new ArrayList<>();
                
                for(GFF gff:gffList)
                {
                    if(gff.getName().equals(selectedItem.substring(selectedItem.indexOf(">")+1,selectedItem.indexOf(")"))))
                        selectedContigGFFList.add(gff);
                }
                //Show selected contig hits
                Util.printGFFTable(gffTable, selectedContigGFFList);
            }
        };
        contigsList.addMouseListener(mouseListener);
//</editor-fold>
        
        //<editor-fold defaultstate="collapsed" desc="Bar Chart">
        
        //Create dataset for the graph
        DefaultCategoryDataset dataset = Util.createDataSet(contigs);
        
        //Find the N50 index in contigs and draw the bar chart
        int N50Index = Util.findN50Index(contigs, N50);
        Util.drawBarChart(dataset, N50Index, GraphPanel);
//</editor-fold>    
                      
    }//GEN-LAST:event_uploadButtonActionPerformed
   
    private void uploadGFFButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_uploadGFFButtonActionPerformed
    {//GEN-HEADEREND:event_uploadGFFButtonActionPerformed
      
        //<editor-fold defaultstate="collapsed" desc="File Chooser for .gff">
//Create File chooser
        JFileChooser chooser = new JFileChooser();

        //Adding a filter that only accepts the relevant file type
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "GFF file", "gff");
        
        chooser.setFileFilter(filter);
        int confirm = chooser.showOpenDialog(null);
        File file = null;
        //If something is selected
        if(JFileChooser.APPROVE_OPTION == confirm)
            //Get the chosen file
            file = chooser.getSelectedFile();
//</editor-fold>
        
        GffLabel.setText("Filename: " + file.getName());
        
        //<editor-fold defaultstate="collapsed" desc="Parsing and printing the GFF list from the file">

        //Parsing the gff file into GFF objects
        try
        {
            gffList = Util.parseGFF(file);
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        //Show all Contig hits from .gff
        Util.printGFFTable(gffTable, gffList);
//</editor-fold>
        
    }//GEN-LAST:event_uploadGFFButtonActionPerformed

    public static void main(String args[])
    {     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {            
                new MainFrame().setVisible(true);               
            }          
        });             
    }
    
    //List to hold the GFF objects that is parsed from uploadGFF button
    List<GFF> gffList = new ArrayList<>();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GffLabel;
    private javax.swing.JPanel GraphPanel;
    private javax.swing.JLabel N50Label;
    private javax.swing.JLabel averagecontigLabel;
    private javax.swing.JTextArea contigSequenceTextArea;
    private javax.swing.JList contigsList;
    private javax.swing.JLabel filenameLabel;
    private javax.swing.JTable gffTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel largestcontigLabel;
    private javax.swing.JLabel numberofcontigLabel;
    private javax.swing.JLabel overallGCLabel;
    private javax.swing.JLabel selectedContigGCLabel;
    private javax.swing.JLabel selectedContigLengthLabel;
    private javax.swing.JLabel shortestcontigLabel;
    private javax.swing.JLabel totallengthLabel;
    private javax.swing.JButton uploadButton;
    private javax.swing.JButton uploadGFFButton;
    // End of variables declaration//GEN-END:variables
}
